$(info ======== Build met.ko ... ========)
MET_DIR := $(wildcard $(src)/$(subst ",,$(CONFIG_MTK_PLATFORM)))

ifeq ($(MET_DIR), mt6761)
MET_DIR := 6765
else ifeq ($(MET_DIR), mt6762)
MET_DIR := 6765
endif

ifneq ($(MET_DIR),)
    MET_PLF_USE := $(shell test -f $(MET_DIR)/Kbuild && echo yes)
    ifeq ($(MET_PLF_USE),yes)
        include $(MET_DIR)/Kbuild
        ccflags-y += -DMET_PLF_USE
    else
        $(info ======== NOT MET_PLF_USE ========)
    endif
endif


MET_CORE := common
obj-m := met.o
ccflags-y += -I$(srctree)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/../vendor/mediatek/kernel_modules/met_drv/4.9/common/
ccflags-y += -I$(srctree)/../vendor/mediatek/kernel_modules/met_drv/4.9/$(MTK_PLATFORM)/
ifeq ($(MTK_PLATFORM), mt6761)
ccflags-y += -I$(srctree)/../vendor/mediatek/kernel_modules/met_drv/4.9/mt6765/
else ifeq ($(MTK_PLATFORM), mt6762)
ccflags-y += -I$(srctree)/../vendor/mediatek/kernel_modules/met_drv/4.9/mt6765/
endif
ccflags-y += $(EXTRA_ARGS) $(EXTRA_CFLAGS)

met-y := $(MET_CORE)/met_main.o \
		 $(MET_CORE)/met_backlight.o \
		 $(MET_CORE)/met_tag_ex.o \
		 $(MET_CORE)/interface.o \
		 $(MET_CORE)/sampler.o \
		 $(MET_CORE)/dummy_header.o \
		 $(MET_CORE)/util.o \
		 $(MET_CORE)/stat.o \
		 $(MET_CORE)/cookie.o \
		 $(MET_CORE)/mem_stat.o \
		 $(MET_CORE)/switch.o \
		 $(MET_CORE)/trace_event.o \
		 $(MET_CORE)/core_plf_init.o \
		 $(MET_CORE)/core_plf_trace.o \
		 $(MET_CORE)/ondiemet.o \
		 $(MET_CORE)/ondiemet_log.o \
		 $(MET_CORE)/sspm/ondiemet_sspm.o

CFLAGS_interface.o += -DMET_USER_EVENT_SUPPORT
CFLAGS_met_tag_ex.o += -DMET_USER_EVENT_SUPPORT

ifeq ($(ARCH), mips)
met-y += $(MET_CORE)/mips_pmu_hw.o
endif #ifeq ($(ARCH), mips)

ifeq ($(ARCH), arm)
ccflags-y += -DCONFIG_MET_ARM_32BIT
met-y += $(MET_CORE)/cpu_pmu.o
met-y += $(MET_CORE)/v7_pmu_hw.o
met-y += $(MET_CORE)/v6_pmu_hw.o
endif #ifeq ($(ARCH), arm)

ifeq ($(ARCH), arm64)
met-y += $(MET_CORE)/cpu_pmu.o
met-y += $(MET_CORE)/v8_pmu_hw.o
endif

met-$(CONFIG_CPU_FREQ) += $(MET_CORE)/power.o


################################################################################
# MET_EMI
################################################################################
MET_EMI := y

met-$(MET_EMI) += $(MET_CORE)/met_emi.o \
				  $(MET_CORE)/mtk_emi_bm.o


################################################################################
# MET_GPU
################################################################################
MET_GPU := y

# for mtk_gpufreq.h
ifneq ("$(wildcard $(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/mtk_gpufreq.h)","")
	ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/
else
	MET_GPU = n
    $(info ======== Missing mtk_gpufreq.h ========)
endif

# for mtk_gpu_utility.h
ifneq ("$(wildcard $(srctree)/drivers/misc/mediatek/include/mt-plat/mtk_gpu_utility.h)","")
	ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
else
	MET_GPU = n
    $(info ======== Missing mtk_gpu_utility.h ========)
endif

met-$(MET_GPU) += $(MET_CORE)/mtk_gpu_metmonitor.o


################################################################################
# MET_VCOREDVFS
################################################################################
MET_VCOREDVFS := y

# for mtk_vcorefs_manager.h
ifneq ("$(wildcard $(MET_VCOREDVFS_INC)/mtk_vcorefs_manager.h)","")
	ccflags-y += -I$(MET_VCOREDVFS_INC)/
else
	MET_VCOREDVFS = n
    $(info ======== Missing mtk_vcorefs_manager.h ========)
endif

# for mtk_vcorefs_governor.h
ifneq ("$(wildcard $(MET_VCOREDVFS_INC)/mtk_vcorefs_governor.h)","")
	ccflags-y += -I$(MET_VCOREDVFS_INC)
else
	MET_VCOREDVFS = n
    $(info ======== Missing mtk_vcorefs_governor.h ========)
endif

# for helio-dvfsrc.h
ifneq ("$(wildcard $(srctree)/drivers/devfreq/helio-dvfsrc.h)","")
	ccflags-y += -I$(srctree)/drivers/devfreq/
else
	MET_VCOREDVFS = n
    $(info ======== Missing helio-dvfsrc.h ========)
endif

met-$(MET_VCOREDVFS) += $(MET_CORE)/met_vcoredvfs.o


################################################################################
# MET_PTPOD
################################################################################
MET_PTPOD := y

# for mtk_gpufreq.h
ifneq ("$(wildcard $(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/mtk_gpufreq.h)","")
	ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/
else
	MET_PTPOD = n
    $(info ======== Missing mtk_gpufreq.h ========)
endif

# for mtk_cpufreq_api.h
ifneq ("$(wildcard $(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/mach/mtk_cpufreq_api.h)","")
	ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
else
	MET_PTPOD = n
    $(info ======== Missing mtk_cpufreq_api.h ========)
endif

# for mtk_cpufreq_config.h
ifneq ("$(wildcard $(MET_PTPOD_INC)/mtk_cpufreq_config.h)","")
	ccflags-y += -I$(MET_PTPOD_INC)
else
	MET_PTPOD = n
    $(info ======== Missing mtk_cpufreq_config.h ========)
endif

met-$(MET_PTPOD) += $(MET_CORE)/met_ptpod.o


################################################################################
# On-die-met SSPM only module
################################################################################
ifeq ($(CONFIG_MTK_TINYSYS_SSPM_SUPPORT),y)
	# for sspm_ipi.h
	subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm
	subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/$(MTK_PLATFORM)
	met-y += $(MET_CORE)/sspm/sspm_ipi_handle.o
	met-y += $(MET_CORE)/sspm/sspm_common.o
	ccflags-y += -DMTK_TINYSYS_SSPM_SUPPORT
endif


ccflags-y += $(foreach v, $(filter MET_%,$(.VARIABLES)), $(if $(filter $($(v)),y),-D$(v)))
