MET_CORE := common

obj-m := met.o

ccflags-y += -DCONFIG_MET_MODULE
ccflags-y += -I$(srctree)/include/

met-y := $(MET_CORE)/met_main.o $(MET_CORE)/interface.o $(MET_CORE)/sampler.o \
	$(MET_CORE)/dummy_header.o $(MET_CORE)/util.o $(MET_CORE)/stat.o $(MET_CORE)/cookie.o \
	$(MET_CORE)/cpu_pmu.o $(MET_CORE)/mem_stat.o $(MET_CORE)/switch.o \
	$(MET_CORE)/trace_event.o $(MET_CORE)/ondiemet.o $(MET_CORE)/ondiemet_log.o $(MET_CORE)/met_backlight.o

CFLAGS_interface.o += -DMET_USER_EVENT_SUPPORT

ifeq ($(ARCH), mips)
met-y += $(MET_CORE)/mips_pmu_hw.o
endif #ifeq ($(ARCH), mips)


ifeq ($(ARCH), arm)
ccflags-y += -DCONFIG_MET_ARM_32BIT
met-y += $(MET_CORE)/v7_pmu_hw.o
met-y += $(MET_CORE)/v6_pmu_hw.o
endif #ifeq ($(ARCH), arm)

ifeq ($(ARCH), arm64)
ccflags-y += -DMET_SUPPORT_CPUPMU_V2
met-y += $(MET_CORE)/v8_pmu_hw.o
met-y += $(MET_CORE)/cpu_pmu_v2.o
met-y += $(MET_CORE)/v8_pmu_hw_v2.o
endif

# MET in module form will use met_tag_new.c
met-y += $(MET_CORE)/met_tag_ex.o
CFLAGS_met_tag_ex.o += -DMET_USER_EVENT_SUPPORT

met-$(CONFIG_CPU_FREQ) += $(MET_CORE)/power.o
